# This workflow is meant to deploy the Web export generated manually and included in the
# repository (in `Builds/PenaltyDemo_WebGL_Brotli`) to GitHub Pages, making the game playable
# directly from the website, and making it easy to integrate as an iFrame elsewhere.

name: Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - pages
      - main
      - master
      - release
    paths:
      - "Builds/PenaltyDemo_WebGL_Brotli"

permissions:
  contents: read
  pages: write
  id-token: write

# Avoid having two deployments running if two commits have been pushed in a small interval
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare WebGL build
        run: |
          mkdir -p public
          cp -r Builds/PenaltyDemo_WebGL_Brotli/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4